/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baeldung_jni_CppAlgoritms */

#ifndef _Included_com_baeldung_jni_CppAlgoritms
#define _Included_com_baeldung_jni_CppAlgoritms
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baeldung_jni_CppAlgoritms
 * Method:    levenshtein
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_baeldung_jni_CppAlgoritms_levenshtein
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
